MonsterManual5e/Models/info_type.cs
using System;
using System.Collections.Generic;

namespace MonsterManual5e.Models
{
    public partial class InfoType
    {
        public InfoType()
        {
            this.XrefMonsterInfo = new List<XrefMonsterInfo>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public int Order { get; set; }

        public string Note { get; set; }

        public virtual ICollection<XrefMonsterInfo> XrefMonsterInfo { get; set; }

    }
}

MonsterManual5e/Models/monster.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MonsterManual5e.Models
{
    public partial class Monster
    {
        public Monster()
        {
            this.XrefMonsterDamageType = new List<XrefMonsterDamageType>();
            this.XrefMonsterInfo = new List<XrefMonsterInfo>();
            this.XrefMonsterLanguage = new List<XrefMonsterLanguage>();
            this.XrefMonsterSense = new List<XrefMonsterSense>();
            this.XrefMonsterSkill = new List<XrefMonsterSkill>();
            this.XrefMonsterSpeed = new List<XrefMonsterSpeed>();
            this.Conditions = new List<Condition>();
            this.Encounters = new List<Encounter>();
            this.DamageType = new List<DamageType>();
            this.DamageType1 = new List<DamageType>();
            this.Tags = new List<Tag>();
            this.DamageType2 = new List<DamageType>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public string UrlName { get; set; }

        public int SizeId { get; set; }

        public int TypeId { get; set; }

        [NotMapped]
        public Alignment Alignment { get; set; }

        public int AlignmentAttitudeId { get; set; }

        public int AlignmentMoralityId { get; set; }

        public int Ac { get; set; }

        public string AcNote { get; set; }

        public int Hp { get; set; }

        public string HpNote { get; set; }

        public int Str { get; set; }

        public int Dex { get; set; }

        public int Con { get; set; }

        public int Int { get; set; }

        public int Wis { get; set; }

        public int Cha { get; set; }

        public int StrSave { get; set; }

        public int DexSave { get; set; }

        public int ConSave { get; set; }

        public int IntSave { get; set; }

        public int WisSave { get; set; }

        public int ChaSave { get; set; }

        public int PassivePerception { get; set; }

        public string LanguageNote { get; set; }

        public float ChallengeRating { get; set; }

        public int ExperiencePoints { get; set; }

        public int TelepathyDistance { get; set; }

        public int SourceId { get; set; }

        public int SourcePage { get; set; }

        public virtual AlignmentAttitude AlignmentAttitude { get; set; }

        public virtual AlignmentMorality AlignmentMorality { get; set; }

        public virtual ICollection<XrefMonsterDamageType> XrefMonsterDamageType { get; set; }

        public virtual ICollection<XrefMonsterInfo> XrefMonsterInfo { get; set; }

        public virtual ICollection<XrefMonsterLanguage> XrefMonsterLanguage { get; set; }

        public virtual ICollection<XrefMonsterSense> XrefMonsterSense { get; set; }

        public virtual ICollection<XrefMonsterSkill> XrefMonsterSkill { get; set; }

        public virtual ICollection<XrefMonsterSpeed> XrefMonsterSpeed { get; set; }

        public virtual Size Size { get; set; }

        public virtual Source Source { get; set; }

        public virtual MonsterType MonsterType { get; set; }

        public virtual ICollection<Condition> Conditions { get; set; }

        public virtual ICollection<Encounter> Encounters { get; set; }

        public virtual ICollection<DamageType> DamageType { get; set; }

        public virtual ICollection<DamageType> DamageType1 { get; set; }

        public virtual ICollection<Tag> Tags { get; set; }

        public virtual ICollection<DamageType> DamageType2 { get; set; }

    }
}

MonsterManual5e/Models/monster_type.cs
using System;
using System.Collections.Generic;

namespace MonsterManual5e.Models
{
    public partial class MonsterType
    {
        public MonsterType()
        {
            this.Monsters = new List<Monster>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public int Order { get; set; }

        public string Note { get; set; }

        public virtual ICollection<Monster> Monsters { get; set; }

    }
}

MonsterManual5e/ViewModels/MonsterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MonsterManual5e.Models;

namespace MonsterManual5e.ViewModels
{
    public class MonsterViewModel
    {
        public Monster Monster { get; set; }

        public ICollection<SelectListItem> AffectTypes { get; set; }

        public ICollection<SelectListItem> Alignments { get; set; }

        public ICollection<SelectListItem> Conditions { get; set; }

        public ICollection<SelectListItem> DamageTypes { get; set; }

        public ICollection<SelectListItem> InfoTypes { get; set; }

        public ICollection<SelectListItem> Languages { get; set; }

        public ICollection<SelectListItem> Senses { get; set; }

        public ICollection<SelectListItem> Sizes { get; set; }

        public ICollection<SelectListItem> Skills { get; set; }

        public ICollection<SelectListItem> Speeds { get; set; }

        public ICollection<SelectListItem> Tags { get; set; }

        public ICollection<SelectListItem> Types { get; set; }

        public int SelectedAlignment { get; set; }

        public ICollection<int> SelectedSenses { get; set; }

        public ICollection<int> SelectedSkills { get; set; }

        public ICollection<int> SelectedLanguages { get; set; }

        public ICollection<int> SelectedSkillsBonuses { get; set; }

        //public ICollection<int> SelectedAffectTypes { get; set; }

        //public ICollection<int> SelectedConditions { get; set; }

        //public ICollection<int> SelectedDamageTypes { get; set; }

        //public ICollection<int> SelectedInfoTypes { get; set; }
        
        //public ICollection<int> SelectedSpeeds { get; set; }

        //public ICollection<int> SelectedTags { get; set; }
    }
}

MonsterManual5e/Controllers/MonsterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MonsterManual5e.Models;
using MonsterManual5e.ViewModels;
using MonsterManual5e.Repositories;
using MonsterManual5e.Helpers;

namespace MonsterManual5e.Controllers
{
    public class MonsterController : Controller
    {
        private MonsterRepository mrepo = new MonsterRepository();

        // GET: Monster
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            MonsterViewModel vm = new MonsterViewModel();
            vm.Monster = new Monster();
            vm.Languages = SelectListBuilder.GetLanguages().ToList();
            vm.Sizes = SelectListBuilder.GetSizes().ToList();
            vm.Types = SelectListBuilder.GetTypes().ToList();
            vm.Alignments = SelectListBuilder.GetAlignments().ToList();
            vm.Senses = SelectListBuilder.GetSenses().ToList();
            vm.Skills = SelectListBuilder.GetSkills().ToList();

            return View(vm);
        }

        public ActionResult Info(int id)
        {
            MonsterViewModel vm = new MonsterViewModel();
            vm.Monster = mrepo.GetMonsterById(id);
            //vm.Languages = SelectListBuilder.GetLanguages().ToList();
            //vm.Sizes = SelectListBuilder.GetSizes().ToList();
            //vm.Types = SelectListBuilder.GetTypes().ToList();
            //vm.Alignments = SelectListBuilder.GetAlignments().ToList();
            //vm.Senses = SelectListBuilder.GetSenses().ToList();
            //vm.Skills = SelectListBuilder.GetSkills().ToList();

            return View(vm);
        }

        public ActionResult Edit(int id)
        {
            MonsterViewModel vm = new MonsterViewModel();
            vm.Monster = mrepo.GetMonsterById(id);
            vm.Languages = SelectListBuilder.GetLanguages().ToList();
            vm.Sizes = SelectListBuilder.GetSizes().ToList();
            vm.Types = SelectListBuilder.GetTypes().ToList();
            vm.Alignments = SelectListBuilder.GetAlignments().ToList();
            vm.Senses = SelectListBuilder.GetSenses().ToList();
            vm.Skills = SelectListBuilder.GetSkills().ToList();
            vm.SelectedSenses = new List<int>();
            vm.SelectedSkills = new List<int>();
            vm.SelectedSkillsBonuses = new List<int>();

            for (int i = 0; i < vm.Monster.XrefMonsterSkill.Count; i++)
            {
                vm.SelectedSkills.Add(vm.Monster.XrefMonsterSkill.ElementAt(i).SkillId);
                vm.SelectedSkillsBonuses.Add(vm.Monster.XrefMonsterSkill.ElementAt(i).Value);
            }

            for (int i = 0; i < vm.Monster.XrefMonsterSense.Count; i++)
            {
                vm.SelectedSenses.Add(vm.Monster.XrefMonsterSense.ElementAt(i).SenseId);
            }

            vm.SelectedAlignment = AlignmentHelper.GetAlignmentOrder(vm.Monster.AlignmentAttitude.Name, vm.Monster.AlignmentMorality.Name);

            return View(vm);
        }

        [HttpPost]
        public ActionResult Edit(MonsterViewModel mvm)
        {

            return Info(mvm.Monster.Id);
        }

        public string GetAlignmentName(string a, string m)
        {
            return AlignmentHelper.GetAlignment(a, m);
        }
    }
}

MonsterManual5e/Views/Monster/Create.cshtml
@model MonsterManual5e.ViewModels.MonsterViewModel
@{
    ViewBag.Title = "Create Monster";
}

<div class="page-header">
    <h1>Create Monster</h1>
</div>

<form>
    @Html.HiddenFor(m => m.Monster.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Monster.Name, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(m => m.Monster.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter the monster's name...", @required = "required" }})
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.Size, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(m => m.Monster.Size, Model.Sizes, htmlAttributes: new { @class = "form-control single-select" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.MonsterType, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(m => m.Monster.MonsterType, Model.Types, htmlAttributes: new { @class = "form-control single-select" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.Alignment, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(m => m.Monster.Alignment, Model.Alignments, htmlAttributes: new { @class = "form-control single-select" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.Ac, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(m => m.Monster.Ac, new { htmlAttributes = new { @class = "form-control", @placeholder = "", @required = "required" } })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.AcNote, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(m => m.Monster.AcNote, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter an optional AC note...", @required = "required" } })
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.Hp, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(m => m.Monster.Hp, new { htmlAttributes = new { @class = "form-control", @placeholder = "", @required = "required" } })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.HpNote, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(m => m.Monster.HpNote, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter an optional HP note...", @required = "required" } })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2 col-xs-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.Str, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(m => m.Monster.Str, new { htmlAttributes = new { @class = "form-control", @placeholder = "", @Value = "10", @required = "required" } })
            </div>
        </div>
        <div class="col-sm-2 col-xs-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.Dex, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(m => m.Monster.Dex, new { htmlAttributes = new { @class = "form-control", @placeholder = "", @Value = "10", @required = "required" } })
            </div>
        </div>
        <div class="col-sm-2 col-xs-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.Con, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(m => m.Monster.Con, new { htmlAttributes = new { @class = "form-control", @placeholder = "", @Value = "10", @required = "required" } })
            </div>
        </div>
        <div class="col-sm-2 col-xs-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.Int, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(m => m.Monster.Int, new { htmlAttributes = new { @class = "form-control", @placeholder = "", @Value = "10", @required = "required" } })
            </div>
        </div>
        <div class="col-sm-2 col-xs-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.Wis, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(m => m.Monster.Wis, new { htmlAttributes = new { @class = "form-control", @placeholder = "", @Value = "10", @required = "required" } })
            </div>
        </div>
        <div class="col-sm-2 col-xs-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.Cha, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(m => m.Monster.Cha, new { htmlAttributes = new { @class = "form-control", @placeholder = "", @Value = "10", @required = "required" } })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.PassivePerception, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(m => m.Monster.PassivePerception, new { htmlAttributes = new { @class = "form-control", @placeholder = "", @required = "required" } })
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                @Html.Label("Languages", htmlAttributes: new { @class = "control-label" })
                @Html.ListBoxFor(m => m.SelectedLanguages, Model.Languages, new { @class = "form-control multi-select" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.Monster.TelepathyDistance, htmlAttributes: new { @class = "control-label" })
                <div class="input-group">                    
                    @Html.EditorFor(m => m.Monster.TelepathyDistance, new { htmlAttributes = new { @class = "form-control", @placeholder = "", @Value = "0" } })
                    <span class="input-group-addon">ft.</span>
                </div>                
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3 col-sm-6">
            <div class="form-group">
                @Html.Label("Senses", htmlAttributes: new { @class = "control-label" })
                @Html.ListBoxFor(m => m.SelectedSenses, Model.Senses, new { @class = "form-control multi-select" })
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <table class="table-condensed">
                <thead>
                    <tr>
                        <th>Sense</th>
                        <th>Distance</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var sense in Model.Senses)
                    {
                        <tr data-sense="@sense.Text">
                            <td>@sense.Text</td>
                            <td>
                                <div class="input-group">
                                    <input class="form-control" type="number" value="0" />
                                    <span class="input-group-addon">ft.</span>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="form-group">
                @Html.Label("Skills", htmlAttributes: new { @class = "control-label" })
                @Html.ListBoxFor(m => m.SelectedSkills, Model.Skills, new { @class = "form-control multi-select" })
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <table class="table-condensed">
                <thead>
                    <tr>
                        <th>Skill</th>
                        <th>Bonus</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var skill in Model.Skills)
                    {
                        <tr data-skill="@skill.Text">
                            <td>@skill.Text</td>
                            <td>
                                <input class="form-control" type="number" value="0" />
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
        
</form>

MonsterManual5e/Views/Monster/Info.cshtml
@model MonsterManual5e.ViewModels.MonsterViewModel
@{
    ViewBag.Title = Model.Monster.Name;
}

<div class="page-header">
    <h1>@Model.Monster.Name</h1>
</div>

<form>
    @Html.HiddenFor(m => m.Monster.Id)
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.Name, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.Name</p>
                    </div>
                </div>
                <div class="col-md-6">
                    @Html.ActionLink("Edit " + Model.Monster.Name, "Edit", "Monster", new { id = Model.Monster.Id }, new { @class = "btn btn-primary" })
                </div>
            </div>            
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.Size, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.Size.Name</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.MonsterType, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.MonsterType.Name</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.Alignment, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Html.Action("GetAlignmentName", "Monster", new { a = Model.Monster.AlignmentAttitude.Name, m = Model.Monster.AlignmentMorality.Name })</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.Ac, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.Ac</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.AcNote, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.AcNote</p>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.Hp, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.Hp</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.HpNote, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.HpNote</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2 col-xs-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.Str, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.Str</p>
                    </div>
                </div>
                <div class="col-sm-2 col-xs-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.Dex, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.Dex</p>
                    </div>
                </div>
                <div class="col-sm-2 col-xs-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.Con, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.Con</p>
                    </div>
                </div>
                <div class="col-sm-2 col-xs-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.Int, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.Int</p>
                    </div>
                </div>
                <div class="col-sm-2 col-xs-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.Wis, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.Wis</p>
                    </div>
                </div>
                <div class="col-sm-2 col-xs-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.Cha, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.Cha</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.PassivePerception, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.PassivePerception</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <p>
                            @Html.Label("Languages", htmlAttributes: new { @class = "control-label" })
                            @foreach (var language in Model.Monster.XrefMonsterLanguage)
                            {
                                @language.Language.Name
                            }
                        </p>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Monster.TelepathyDistance, htmlAttributes: new { @class = "control-label" })
                        <p class="form-control-static">@Model.Monster.TelepathyDistance ft.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <table class="table-condensed">
                        <thead>
                            <tr>
                                <th>Sense</th>
                                <th>Distance</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var monsterSense in Model.Monster.XrefMonsterSense)
                            {
                                <tr data-sense="@monsterSense.Sense.Name">
                                    <td>@monsterSense.Sense.Name</td>
                                    <td>@monsterSense.Value</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="col-sm-4">
                    <table class="table-condensed">
                        <thead>
                            <tr>
                                <th>Skill</th>
                                <th>Bonus</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var monsterSkill in Model.Monster.XrefMonsterSkill)
                            {
                                <tr data-skill="@monsterSkill.Skill.Name">
                                    <td>@monsterSkill.Skill.Name</td>
                                    <td>@monsterSkill.Value.ToString("+0;-0;0")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="col-sm-4">
                    <table class="table-condensed">
                        <thead>
                            <tr>
                                <th>Skill</th>
                                <th>Bonus</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var monsterSpeed in Model.Monster.XrefMonsterSpeed)
                            {
                                <tr data-skill="@monsterSpeed.Speed.Name">
                                    <td>@monsterSpeed.Speed.Name</td>
                                    <td>@monsterSpeed.Value ft.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</form>